import { storage as localStorageService } from './storage';
import {
    getAllDocuments,
    getDocument,
    addDocument,
    updateDocument,
    deleteDocument,
    getDocumentsWhere,
    deleteDocumentsWhere,
    isFirestoreAvailable
} from './firestoreHelpers';

/**
 * Hybrid Storage Service
 * Reads from Firestore first, falls back to localStorage
 * Writes to both Firestore and localStorage for data safety
 */

// Track Firestore availability
let firestoreEnabled = true;

// Check Firestore availability on load
isFirestoreAvailable().then(available => {
    firestoreEnabled = available;
    if (!available) {
        console.warn('Firestore not available, using localStorage only');
    }
});

/**
 * Hybrid wrapper for async/sync operations
 * Tries Firestore first, falls back to localStorage
 */
const hybridGet = async (firestoreOperation, localStorageOperation) => {
    if (firestoreEnabled) {
        try {
            return await firestoreOperation();
        } catch (error) {
            console.warn('Firestore read failed, falling back to localStorage:', error.message);
            firestoreEnabled = false;
            return localStorageOperation();
        }
    }
    return localStorageOperation();
};

/**
 * Hybrid write operation
 * Writes to both Firestore and localStorage
 */
const hybridWrite = async (firestoreOperation, localStorageOperation) => {
    // Always write to localStorage first (for immediate UI update)
    const localResult = localStorageOperation();

    // Then sync to Firestore in background
    if (firestoreEnabled) {
        try {
            await firestoreOperation();
        } catch (error) {
            console.error('Firestore write failed (localStorage updated):', error.message);
            // Don't disable Firestore for write failures, just log
        }
    }

    return localResult;
};

export const hybridStorage = {
    // ===== PROJECTS =====

    getProjects: async () => {
        return hybridGet(
            () => getAllDocuments('projects'),
            () => localStorageService.getProjects()
        );
    },

    getProject: async (id) => {
        return hybridGet(
            () => getDocument('projects', id),
            () => localStorageService.getProject(id)
        );
    },

    addProject: async (project) => {
        return hybridWrite(
            async () => {
                // Use the ID generated by localStorage for consistency
                const localResult = localStorageService.addProject(project);
                await addDocument('projects', localResult, localResult.id);
                return localResult;
            },
            () => localStorageService.addProject(project)
        );
    },

    updateProject: async (id, updates) => {
        return hybridWrite(
            async () => {
                await updateDocument('projects', id, updates);
                return localStorageService.updateProject(id, updates);
            },
            () => localStorageService.updateProject(id, updates)
        );
    },

    deleteProject: async (id) => {
        return hybridWrite(
            async () => {
                // Delete project
                await deleteDocument('projects', id);

                // Cascade delete related data
                await Promise.all([
                    deleteDocumentsWhere('expenses', 'projectId', id),
                    deleteDocumentsWhere('payments', 'projectId', id),
                    deleteDocumentsWhere('logs', 'projectId', id),
                    deleteDocumentsWhere('tasks', 'projectId', id),
                    deleteDocumentsWhere('milestones', 'projectId', id)
                ]);

                localStorageService.deleteProject(id);
            },
            () => localStorageService.deleteProject(id)
        );
    },

    // ===== LOGS =====

    getLogs: async (projectId = null) => {
        if (projectId) {
            return hybridGet(
                () => getDocumentsWhere('logs', 'projectId', projectId),
                () => localStorageService.getLogs(projectId)
            );
        }
        return hybridGet(
            () => getAllDocuments('logs'),
            () => JSON.parse(localStorage.getItem('bb_logs') || '[]')
        );
    },

    addLog: async (log) => {
        return hybridWrite(
            async () => {
                const localResult = localStorageService.addLog(log);
                await addDocument('logs', localResult, localResult.id);
                return localResult;
            },
            () => localStorageService.addLog(log)
        );
    },

    updateLog: async (id, updatedLog) => {
        return hybridWrite(
            async () => {
                await updateDocument('logs', id, updatedLog);
                return localStorageService.updateLog(id, updatedLog);
            },
            () => localStorageService.updateLog(id, updatedLog)
        );
    },

    deleteLog: async (id) => {
        return hybridWrite(
            async () => {
                await deleteDocument('logs', id);
                localStorageService.deleteLog(id);
            },
            () => localStorageService.deleteLog(id)
        );
    },

    // ===== EXPENSES =====

    getExpenses: async () => {
        return hybridGet(
            () => getAllDocuments('expenses'),
            () => localStorageService.getExpenses()
        );
    },

    addExpense: async (expense) => {
        return hybridWrite(
            async () => {
                const localResult = localStorageService.addExpense(expense);
                await addDocument('expenses', localResult, localResult.id);
                return localResult;
            },
            () => localStorageService.addExpense(expense)
        );
    },

    updateExpense: async (id, updatedExpense) => {
        return hybridWrite(
            async () => {
                await updateDocument('expenses', id, updatedExpense);
                return localStorageService.updateExpense(id, updatedExpense);
            },
            () => localStorageService.updateExpense(id, updatedExpense)
        );
    },

    deleteExpense: async (id) => {
        return hybridWrite(
            async () => {
                await deleteDocument('expenses', id);
                localStorageService.deleteExpense(id);
            },
            () => localStorageService.deleteExpense(id)
        );
    },

    // ===== PAYMENTS =====

    getPayments: async () => {
        return hybridGet(
            () => getAllDocuments('payments'),
            () => localStorageService.getPayments()
        );
    },

    getProjectPayments: async (projectId) => {
        return hybridGet(
            () => getDocumentsWhere('payments', 'projectId', projectId),
            () => localStorageService.getProjectPayments(projectId)
        );
    },

    addPayment: async (payment) => {
        return hybridWrite(
            async () => {
                const localResult = localStorageService.addPayment(payment);
                await addDocument('payments', localResult, localResult.id);
                return localResult;
            },
            () => localStorageService.addPayment(payment)
        );
    },

    updatePayment: async (id, updatedPayment) => {
        return hybridWrite(
            async () => {
                await updateDocument('payments', id, updatedPayment);
                return localStorageService.updatePayment(id, updatedPayment);
            },
            () => localStorageService.updatePayment(id, updatedPayment)
        );
    },

    deletePayment: async (id) => {
        return hybridWrite(
            async () => {
                await deleteDocument('payments', id);
                localStorageService.deletePayment(id);
            },
            () => localStorageService.deletePayment(id)
        );
    },

    // ===== MATERIALS =====

    getMaterials: async () => {
        return hybridGet(
            () => getAllDocuments('materials'),
            () => localStorageService.getMaterials()
        );
    },

    addMaterial: async (material) => {
        return hybridWrite(
            async () => {
                const localResult = localStorageService.addMaterial(material);
                await addDocument('materials', localResult, localResult.id);
                return localResult;
            },
            () => localStorageService.addMaterial(material)
        );
    },

    updateStock: async (id, qty, type) => {
        return hybridWrite(
            async () => {
                const localResult = localStorageService.updateStock(id, qty, type);
                if (localResult) {
                    await updateDocument('materials', id, localResult);
                }
                return localResult;
            },
            () => localStorageService.updateStock(id, qty, type)
        );
    },

    deleteMaterial: async (id) => {
        return hybridWrite(
            async () => {
                await deleteDocument('materials', id);
                localStorageService.deleteMaterial(id);
            },
            () => localStorageService.deleteMaterial(id)
        );
    },

    transferTool: async (itemId, fromProjectId, toProjectId, quantity) => {
        return hybridWrite(
            async () => {
                const localResult = localStorageService.transferTool(itemId, fromProjectId, toProjectId, quantity);
                if (localResult) {
                    await updateDocument('materials', itemId, localResult);
                }
                return localResult;
            },
            () => localStorageService.transferTool(itemId, fromProjectId, toProjectId, quantity)
        );
    },

    // ===== TASKS =====

    getTasks: async () => {
        return hybridGet(
            () => getAllDocuments('tasks'),
            () => localStorageService.getTasks()
        );
    },

    addTask: async (task) => {
        return hybridWrite(
            async () => {
                const localResult = localStorageService.addTask(task);
                await addDocument('tasks', localResult, localResult.id);
                return localResult;
            },
            () => localStorageService.addTask(task)
        );
    },

    updateTask: async (id, updatedTask) => {
        return hybridWrite(
            async () => {
                await updateDocument('tasks', id, updatedTask);
                return localStorageService.updateTask(id, updatedTask);
            },
            () => localStorageService.updateTask(id, updatedTask)
        );
    },

    deleteTask: async (id) => {
        return hybridWrite(
            async () => {
                await deleteDocument('tasks', id);
                localStorageService.deleteTask(id);
            },
            () => localStorageService.deleteTask(id)
        );
    },

    toggleTaskComplete: async (id) => {
        return hybridWrite(
            async () => {
                const localResult = localStorageService.toggleTaskComplete(id);
                if (localResult) {
                    await updateDocument('tasks', id, localResult);
                }
                return localResult;
            },
            () => localStorageService.toggleTaskComplete(id)
        );
    },

    // ===== MILESTONES =====

    getMilestones: async () => {
        return hybridGet(
            () => getAllDocuments('milestones'),
            () => localStorageService.getMilestones()
        );
    },

    getProjectMilestones: async (projectId) => {
        return hybridGet(
            () => getDocumentsWhere('milestones', 'projectId', projectId),
            () => localStorageService.getProjectMilestones(projectId)
        );
    },

    addMilestone: async (milestone) => {
        return hybridWrite(
            async () => {
                const localResult = localStorageService.addMilestone(milestone);
                await addDocument('milestones', localResult, localResult.id);
                return localResult;
            },
            () => localStorageService.addMilestone(milestone)
        );
    },

    updateMilestone: async (id, updates) => {
        return hybridWrite(
            async () => {
                await updateDocument('milestones', id, updates);
                return localStorageService.updateMilestone(id, updates);
            },
            () => localStorageService.updateMilestone(id, updates)
        );
    },

    deleteMilestone: async (id) => {
        return hybridWrite(
            async () => {
                await deleteDocument('milestones', id);
                localStorageService.deleteMilestone(id);
            },
            () => localStorageService.deleteMilestone(id)
        );
    },

    updateMilestoneStatus: async (milestoneId) => {
        return hybridWrite(
            async () => {
                const localResult = localStorageService.updateMilestoneStatus(milestoneId);
                if (localResult) {
                    await updateDocument('milestones', milestoneId, localResult);
                }
                return localResult;
            },
            () => localStorageService.updateMilestoneStatus(milestoneId)
        );
    },

    createMilestoneTemplate: async (projectId, templateType, projectBudget) => {
        return hybridWrite(
            async () => {
                const localResults = localStorageService.createMilestoneTemplate(projectId, templateType, projectBudget);
                // Add all milestones to Firestore
                await Promise.all(
                    localResults.map(milestone => addDocument('milestones', milestone, milestone.id))
                );
                return localResults;
            },
            () => localStorageService.createMilestoneTemplate(projectId, templateType, projectBudget)
        );
    },

    // ===== VENDORS =====

    getVendors: async () => {
        return hybridGet(
            () => getAllDocuments('vendors'),
            () => localStorageService.getVendors()
        );
    },

    addVendor: async (vendor) => {
        return hybridWrite(
            async () => {
                const localResult = localStorageService.addVendor(vendor);
                await addDocument('vendors', localResult, localResult.id);
                return localResult;
            },
            () => localStorageService.addVendor(vendor)
        );
    },

    deleteVendor: async (id) => {
        return hybridWrite(
            async () => {
                await deleteDocument('vendors', id);
                localStorageService.deleteVendor(id);
            },
            () => localStorageService.deleteVendor(id)
        );
    },

    // ===== QUOTES =====

    getQuotes: async () => {
        return hybridGet(
            () => getAllDocuments('quotes'),
            () => localStorageService.getQuotes()
        );
    },

    addQuote: async (quote) => {
        return hybridWrite(
            async () => {
                const localResult = localStorageService.addQuote(quote);
                await addDocument('quotes', localResult, localResult.id);
                return localResult;
            },
            () => localStorageService.addQuote(quote)
        );
    },

    deleteQuote: async (id) => {
        return hybridWrite(
            async () => {
                await deleteDocument('quotes', id);
                localStorageService.deleteQuote(id);
            },
            () => localStorageService.deleteQuote(id)
        );
    },

    // ===== PHASES =====

    addPhase: async (projectId, phase) => {
        return hybridWrite(
            async () => {
                const localResult = localStorageService.addPhase(projectId, phase);
                // Update the project document in Firestore
                const project = await getDocument('projects', projectId);
                if (project) {
                    await updateDocument('projects', projectId, { phases: project.phases });
                }
                return localResult;
            },
            () => localStorageService.addPhase(projectId, phase)
        );
    },

    updatePhase: async (projectId, phaseId, updates) => {
        return hybridWrite(
            async () => {
                const localResult = localStorageService.updatePhase(projectId, phaseId, updates);
                const project = await getDocument('projects', projectId);
                if (project) {
                    await updateDocument('projects', projectId, { phases: project.phases });
                }
                return localResult;
            },
            () => localStorageService.updatePhase(projectId, phaseId, updates)
        );
    },

    deletePhase: async (projectId, phaseId) => {
        return hybridWrite(
            async () => {
                localStorageService.deletePhase(projectId, phaseId);
                const project = await getDocument('projects', projectId);
                if (project) {
                    await updateDocument('projects', projectId, { phases: project.phases });
                }
            },
            () => localStorageService.deletePhase(projectId, phaseId)
        );
    },

    // ===== IMPORT/EXPORT =====

    exportData: () => {
        // Export always uses localStorage for now
        return localStorageService.exportData();
    },

    importData: (jsonData) => {
        // Import always uses localStorage for now
        return localStorageService.importData(jsonData);
    }
};

// Export as default storage service
export { hybridStorage as storage };
