import { storage as localStorageService } from './storage';
import {
    getAllDocuments,
    getDocument,
    addDocument,
    updateDocument,
    deleteDocument,
    getDocumentsWhere,
    deleteDocumentsWhere,
    isFirestoreAvailable
} from './firestoreHelpers';

/**
 * Hybrid Storage Service
 * Reads from Firestore first, falls back to localStorage
 * Writes to both Firestore and localStorage for data safety
 */

// Track Firestore availability
let firestoreEnabled = true;

// Check Firestore availability on load
isFirestoreAvailable().then(available => {
    firestoreEnabled = available;
    if (!available) {
        console.warn('Firestore not available, using localStorage only');
    }
});

/**
 * Hybrid wrapper for async/sync operations
 * Tries Firestore first, falls back to localStorage
 */
const hybridGet = async (firestoreOperation, localStorageOperation) => {
    if (firestoreEnabled) {
        try {
            return await firestoreOperation();
        } catch (error) {
            console.warn('Firestore read failed, falling back to localStorage:', error.message);
            firestoreEnabled = false;
            return localStorageOperation();
        }
    }
    return localStorageOperation();
};

/**
 * Hybrid write operation
 * Writes to both Firestore and localStorage
 */
const hybridWrite = async (firestoreOperation, localStorageOperation) => {
    // Always write to localStorage first (for immediate UI update)
    const localResult = localStorageOperation();

    // Then sync to Firestore in background
    if (firestoreEnabled) {
        try {
            await firestoreOperation(localResult);
        } catch (error) {
            console.error('Firestore write failed (localStorage updated):', error.message);
            // Don't disable Firestore for write failures, just log
        }
    }

    return localResult;
};

export const hybridStorage = {
    // ===== PROJECTS =====

    getProjects: async () => {
        return hybridGet(
            () => getAllDocuments('projects'),
            () => localStorageService.getProjects()
        );
    },

    getProject: async (id) => {
        return hybridGet(
            () => getDocument('projects', id),
            () => localStorageService.getProject(id)
        );
    },

    addProject: async (project) => {
        return hybridWrite(
            async (localResult) => {
                // Use the ID generated by localStorage for consistency
                await addDocument('projects', localResult, localResult.id);
                return localResult;
            },
            () => localStorageService.addProject(project)
        );
    },

    updateProject: async (id, updates) => {
        return hybridWrite(
            async (localResult) => {
                await updateDocument('projects', id, updates);
                return localResult;
            },
            () => localStorageService.updateProject(id, updates)
        );
    },

    deleteProject: async (id) => {
        return hybridWrite(
            async () => {
                // Delete project
                await deleteDocument('projects', id);

                // Cascade delete related data
                await Promise.all([
                    deleteDocumentsWhere('expenses', 'projectId', id),
                    deleteDocumentsWhere('payments', 'projectId', id),
                    deleteDocumentsWhere('logs', 'projectId', id),
                    deleteDocumentsWhere('tasks', 'projectId', id),
                    deleteDocumentsWhere('milestones', 'projectId', id)
                ]);
            },
            () => localStorageService.deleteProject(id)
        );
    },

    // ===== LOGS =====

    getLogs: async (projectId = null) => {
        if (projectId) {
            return hybridGet(
                () => getDocumentsWhere('logs', 'projectId', projectId),
                () => localStorageService.getLogs(projectId)
            );
        }
        return hybridGet(
            () => getAllDocuments('logs'),
            () => JSON.parse(localStorage.getItem('bb_logs') || '[]')
        );
    },

    addLog: async (log) => {
        return hybridWrite(
            async (localResult) => {
                await addDocument('logs', localResult, localResult.id);
                return localResult;
            },
            () => localStorageService.addLog(log)
        );
    },

    updateLog: async (id, updatedLog) => {
        return hybridWrite(
            async (localResult) => {
                await updateDocument('logs', id, updatedLog);
                return localResult;
            },
            () => localStorageService.updateLog(id, updatedLog)
        );
    },

    deleteLog: async (id) => {
        return hybridWrite(
            async () => {
                await deleteDocument('logs', id);
            },
            () => localStorageService.deleteLog(id)
        );
    },

    // ===== EXPENSES =====

    getExpenses: async () => {
        return hybridGet(
            () => getAllDocuments('expenses'),
            () => localStorageService.getExpenses()
        );
    },

    addExpense: async (expense) => {
        return hybridWrite(
            async (localResult) => {
                await addDocument('expenses', localResult, localResult.id);

                // Update project spent amount in Firestore
                if (expense.projectId) {
                    const project = await getDocument('projects', expense.projectId);
                    if (project) {
                        const newSpent = (project.spent || 0) + Number(expense.amount);
                        await updateDocument('projects', expense.projectId, { spent: newSpent });
                    }
                }

                return localResult;
            },
            () => localStorageService.addExpense(expense)
        );
    },

    updateExpense: async (id, updatedExpense) => {
        return hybridWrite(
            async (localResult) => {
                const oldExpense = await getDocument('expenses', id);
                await updateDocument('expenses', id, updatedExpense);

                // Update project spent amount if amount changed
                if (oldExpense && updatedExpense.amount && Number(oldExpense.amount) !== Number(updatedExpense.amount)) {
                    const projectId = updatedExpense.projectId || oldExpense.projectId;
                    if (projectId) {
                        const project = await getDocument('projects', projectId);
                        if (project) {
                            const diff = Number(updatedExpense.amount) - Number(oldExpense.amount);
                            const newSpent = (project.spent || 0) + diff;
                            await updateDocument('projects', projectId, { spent: newSpent });
                        }
                    }
                }

                return localResult;
            },
            () => localStorageService.updateExpense(id, updatedExpense)
        );
    },

    deleteExpense: async (id) => {
        return hybridWrite(
            async () => {
                // Get expense details before deleting
                const expense = await getDocument('expenses', id);

                await deleteDocument('expenses', id);

                // Update project spent amount
                if (expense && expense.projectId) {
                    const project = await getDocument('projects', expense.projectId);
                    if (project) {
                        const newSpent = (project.spent || 0) - Number(expense.amount);
                        await updateDocument('projects', expense.projectId, { spent: newSpent });
                    }
                }
            },
            () => localStorageService.deleteExpense(id)
        );
    },

    // ===== PAYMENTS =====

    getPayments: async () => {
        return hybridGet(
            () => getAllDocuments('payments'),
            () => localStorageService.getPayments()
        );
    },

    getProjectPayments: async (projectId) => {
        return hybridGet(
            () => getDocumentsWhere('payments', 'projectId', projectId),
            () => localStorageService.getProjectPayments(projectId)
        );
    },

    addPayment: async (payment) => {
        return hybridWrite(
            async (localResult) => {
                await addDocument('payments', localResult, localResult.id);

                // Update project received amount in Firestore
                if (payment.projectId) {
                    const project = await getDocument('projects', payment.projectId);
                    if (project) {
                        const newReceived = (project.received || 0) + Number(payment.amount);
                        await updateDocument('projects', payment.projectId, { received: newReceived });
                    }
                }

                return localResult;
            },
            () => localStorageService.addPayment(payment)
        );
    },

    updatePayment: async (id, updatedPayment) => {
        return hybridWrite(
            async (localResult) => {
                const oldPayment = await getDocument('payments', id);
                await updateDocument('payments', id, updatedPayment);

                // Update project received amount if amount changed
                if (oldPayment && updatedPayment.amount && Number(oldPayment.amount) !== Number(updatedPayment.amount)) {
                    const projectId = updatedPayment.projectId || oldPayment.projectId;
                    if (projectId) {
                        const project = await getDocument('projects', projectId);
                        if (project) {
                            const diff = Number(updatedPayment.amount) - Number(oldPayment.amount);
                            const newReceived = (project.received || 0) + diff;
                            await updateDocument('projects', projectId, { received: newReceived });
                        }
                    }
                }

                return localResult;
            },
            () => localStorageService.updatePayment(id, updatedPayment)
        );
    },

    deletePayment: async (id) => {
        return hybridWrite(
            async () => {
                // Get payment details before deleting
                const payment = await getDocument('payments', id);

                await deleteDocument('payments', id);

                // Update project received amount
                if (payment && payment.projectId) {
                    const project = await getDocument('projects', payment.projectId);
                    if (project) {
                        const newReceived = (project.received || 0) - Number(payment.amount);
                        await updateDocument('projects', payment.projectId, { received: newReceived });
                    }
                }
            },
            () => localStorageService.deletePayment(id)
        );
    },

    // ===== MATERIALS =====

    getMaterials: async () => {
        return hybridGet(
            () => getAllDocuments('materials'),
            () => localStorageService.getMaterials()
        );
    },

    addMaterial: async (material) => {
        return hybridWrite(
            async (localResult) => {
                await addDocument('materials', localResult, localResult.id);
                return localResult;
            },
            () => localStorageService.addMaterial(material)
        );
    },

    updateMaterial: async (id, updates) => {
        return hybridWrite(
            async (localResult) => {
                await updateDocument('materials', id, updates);
                return localResult;
            },
            () => {
                // Update in localStorage
                const materials = JSON.parse(localStorage.getItem('bb_materials') || '[]');
                const index = materials.findIndex(m => m.id === id);
                if (index !== -1) {
                    materials[index] = { ...materials[index], ...updates };
                    localStorage.setItem('bb_materials', JSON.stringify(materials));
                    return materials[index];
                }
                return null;
            }
        );
    },

    updateStock: async (id, qty, type) => {
        return hybridWrite(
            async (localResult) => {
                if (localResult) {
                    await updateDocument('materials', id, localResult);
                }
                return localResult;
            },
            () => localStorageService.updateStock(id, qty, type)
        );
    },

    deleteMaterial: async (id) => {
        return hybridWrite(
            async () => {
                await deleteDocument('materials', id);
            },
            () => localStorageService.deleteMaterial(id)
        );
    },

    transferTool: async (itemId, fromProjectId, toProjectId, quantity) => {
        return hybridWrite(
            async (localResult) => {
                if (localResult) {
                    await updateDocument('materials', itemId, localResult);
                }
                return localResult;
            },
            () => localStorageService.transferTool(itemId, fromProjectId, toProjectId, quantity)
        );
    },

    // ===== TASKS =====

    getTasks: async () => {
        return hybridGet(
            () => getAllDocuments('tasks'),
            () => localStorageService.getTasks()
        );
    },

    addTask: async (task) => {
        return hybridWrite(
            async (localResult) => {
                await addDocument('tasks', localResult, localResult.id);
                return localResult;
            },
            () => localStorageService.addTask(task)
        );
    },

    updateTask: async (id, updatedTask) => {
        return hybridWrite(
            async (localResult) => {
                await updateDocument('tasks', id, updatedTask);
                return localResult;
            },
            () => localStorageService.updateTask(id, updatedTask)
        );
    },

    deleteTask: async (id) => {
        return hybridWrite(
            async () => {
                await deleteDocument('tasks', id);
            },
            () => localStorageService.deleteTask(id)
        );
    },

    toggleTaskComplete: async (id) => {
        return hybridWrite(
            async (localResult) => {
                if (localResult) {
                    await updateDocument('tasks', id, localResult);
                }
                return localResult;
            },
            () => localStorageService.toggleTaskComplete(id)
        );
    },

    // ===== MILESTONES =====

    getMilestones: async () => {
        return hybridGet(
            () => getAllDocuments('milestones'),
            () => localStorageService.getMilestones()
        );
    },

    getProjectMilestones: async (projectId) => {
        return hybridGet(
            () => getDocumentsWhere('milestones', 'projectId', projectId),
            () => localStorageService.getProjectMilestones(projectId)
        );
    },

    addMilestone: async (milestone) => {
        return hybridWrite(
            async (localResult) => {
                await addDocument('milestones', localResult, localResult.id);
                return localResult;
            },
            () => localStorageService.addMilestone(milestone)
        );
    },

    updateMilestone: async (id, updates) => {
        return hybridWrite(
            async (localResult) => {
                await updateDocument('milestones', id, updates);
                return localResult;
            },
            () => localStorageService.updateMilestone(id, updates)
        );
    },

    deleteMilestone: async (id) => {
        return hybridWrite(
            async () => {
                await deleteDocument('milestones', id);
            },
            () => localStorageService.deleteMilestone(id)
        );
    },

    updateMilestoneStatus: async (milestoneId) => {
        return hybridWrite(
            async (localResult) => {
                if (localResult) {
                    await updateDocument('milestones', milestoneId, localResult);
                }
                return localResult;
            },
            () => localStorageService.updateMilestoneStatus(milestoneId)
        );
    },

    createMilestoneTemplate: async (projectId, templateType, projectBudget) => {
        return hybridWrite(
            async (localResults) => {
                // Add all milestones to Firestore
                await Promise.all(
                    localResults.map(milestone => addDocument('milestones', milestone, milestone.id))
                );
                return localResults;
            },
            () => localStorageService.createMilestoneTemplate(projectId, templateType, projectBudget)
        );
    },

    // ===== VENDORS =====

    getVendors: async () => {
        return hybridGet(
            () => getAllDocuments('vendors'),
            () => localStorageService.getVendors()
        );
    },

    addVendor: async (vendor) => {
        return hybridWrite(
            async (localResult) => {
                await addDocument('vendors', localResult, localResult.id);
                return localResult;
            },
            () => localStorageService.addVendor(vendor)
        );
    },

    deleteVendor: async (id) => {
        return hybridWrite(
            async () => {
                await deleteDocument('vendors', id);
            },
            () => localStorageService.deleteVendor(id)
        );
    },

    // ===== QUOTES =====

    getQuotes: async () => {
        return hybridGet(
            () => getAllDocuments('quotes'),
            () => localStorageService.getQuotes()
        );
    },

    addQuote: async (quote) => {
        return hybridWrite(
            async (localResult) => {
                await addDocument('quotes', localResult, localResult.id);
                return localResult;
            },
            () => localStorageService.addQuote(quote)
        );
    },

    deleteQuote: async (id) => {
        return hybridWrite(
            async () => {
                await deleteDocument('quotes', id);
            },
            () => localStorageService.deleteQuote(id)
        );
    },

    // ===== PHASES =====

    addPhase: async (projectId, phase) => {
        return hybridWrite(
            async (localResult) => {
                // Update the project document in Firestore
                const project = await getDocument('projects', projectId);
                if (project) {
                    const currentPhases = project.phases || [];
                    const updatedPhases = [...currentPhases, localResult];
                    await updateDocument('projects', projectId, { phases: updatedPhases });
                }
                return localResult;
            },
            () => localStorageService.addPhase(projectId, phase)
        );
    },

    updatePhase: async (projectId, phaseId, updates) => {
        return hybridWrite(
            async (localResult) => {
                const project = await getDocument('projects', projectId);
                if (project && project.phases) {
                    const updatedPhases = project.phases.map(p =>
                        p.id === phaseId ? { ...p, ...updates } : p
                    );
                    await updateDocument('projects', projectId, { phases: updatedPhases });
                }
                return localResult;
            },
            () => localStorageService.updatePhase(projectId, phaseId, updates)
        );
    },

    deletePhase: async (projectId, phaseId) => {
        return hybridWrite(
            async () => {
                const project = await getDocument('projects', projectId);
                if (project && project.phases) {
                    const updatedPhases = project.phases.filter(p => p.id !== phaseId);
                    await updateDocument('projects', projectId, { phases: updatedPhases });
                }
            },
            () => localStorageService.deletePhase(projectId, phaseId)
        );
    },

    // ===== IMPORT/EXPORT =====

    exportData: () => {
        // Export always uses localStorage for now
        return localStorageService.exportData();
    },

    importData: async (jsonData) => {
        // Import to localStorage first
        const success = localStorageService.importData(jsonData);

        if (!success) {
            return success;
        }

        // Recalculate project totals from imported data
        try {
            const projects = jsonData.projects || [];
            const expenses = jsonData.expenses || [];
            const payments = jsonData.payments || [];

            // Recalculate spent and received for each project
            const updatedProjects = projects.map(project => {
                const projectExpenses = expenses.filter(e => e.projectId === project.id);
                const projectPayments = payments.filter(p => p.projectId === project.id);

                const spent = projectExpenses.reduce((sum, e) => sum + Number(e.amount || 0), 0);
                const received = projectPayments.reduce((sum, p) => sum + Number(p.amount || 0), 0);

                return { ...project, spent, received };
            });

            // Update localStorage with recalculated values
            localStorage.setItem('bb_projects', JSON.stringify(updatedProjects));

            // Sync imported data to Firestore
            if (firestoreEnabled) {
                const collections = ['projects', 'expenses', 'materials', 'logs', 'tasks', 'milestones', 'payments', 'vendors', 'quotes'];

                for (const collectionName of collections) {
                    const data = collectionName === 'projects' ? updatedProjects : (jsonData[collectionName] || []);
                    if (data.length > 0) {
                        // Add each document to Firestore
                        await Promise.all(
                            data.map(item => addDocument(collectionName, item, item.id))
                        );
                    }
                }

                console.log('Data imported and synced to Firestore successfully');
            }
        } catch (error) {
            console.error('Failed to recalculate project totals or sync to Firestore:', error);
        }

        return success;
    },

    // ===== SYNC =====
    syncFromFirestore: async () => {
        if (!firestoreEnabled) return false;

        try {
            const collections = ['projects', 'expenses', 'materials', 'logs', 'tasks', 'milestones', 'payments', 'vendors', 'quotes'];

            for (const collectionName of collections) {
                const docs = await getAllDocuments(collectionName);
                if (docs.length > 0) {
                    // Map collection name to storage key
                    let storageKey = '';
                    switch (collectionName) {
                        case 'projects': storageKey = 'bb_projects'; break;
                        case 'expenses': storageKey = 'bb_expenses'; break;
                        case 'materials': storageKey = 'bb_materials'; break;
                        case 'logs': storageKey = 'bb_logs'; break;
                        case 'tasks': storageKey = 'bb_tasks'; break;
                        case 'payments': storageKey = 'bb_payments'; break;
                        case 'vendors': storageKey = 'bb_vendors'; break;
                        case 'quotes': storageKey = 'bb_quotes'; break;
                        case 'milestones': storageKey = 'bb_milestones'; break;
                    }

                    if (storageKey) {
                        localStorage.setItem(storageKey, JSON.stringify(docs));
                    }
                }
            }
            console.log('Synced from Firestore to localStorage');
            return true;
        } catch (error) {
            console.error('Sync failed:', error);
            return false;
        }
    }
};

// Export as default storage service
export { hybridStorage as storage };
